# Generated by Django 6.0.1 on 2026-01-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_callbacklog'),
        ('payments', '0002_alter_paymenttransaction_id'),
    ]

    operations = [
    ]
